import type { Metadata } from 'next'
import LegalPage, { type Section } from '../_components/LegalPage'

export const metadata: Metadata = {
  title: 'Privacy',
  description:
    'What BureauAI collects, who processes it, and what we do not do with it.',
  alternates: { canonical: '/privacy' },
}

const SECTIONS: Section[] = [
  {
    heading: 'What we collect',
    paragraphs: [
      'Two things, and only when you hand them over.',
    ],
    bullets: [
      'Waitlist form — your email address, and the optional note describing your situation.',
      'Compliance audit — the four answers you select: business type, borough, stage, and current situation. The audit asks for no name, no address, no documents and no account.',
      'Standard server and hosting logs generated by our host, including IP address and user agent, retained for operational and security purposes.',
    ],
  },
  {
    heading: 'Who processes it',
    paragraphs: [
      'BureauAI is a small team and we use third-party processors rather than running this infrastructure ourselves. Each receives only what it needs:',
    ],
    bullets: [
      'Resend — stores your waitlist email address and delivers our notification of your signup. Subject to their privacy terms.',
      'Google (Gemini API) — receives the four audit answers in order to generate your compliance snapshot. It does not receive your email address.',
      'Vercel — hosts the site and processes the request logs described above.',
    ],
  },
  {
    heading: 'What we do not do',
    bullets: [
      'We do not sell your information, and we do not share it with data brokers or advertisers.',
      'We do not connect your audit answers to your email address unless you submit both and we contact you about them.',
      'We do not run third-party advertising or cross-site tracking on this site.',
      'We do not submit anything to any government agency on your behalf. No filing integrations exist today.',
    ],
  },
  {
    heading: 'How long we keep it',
    paragraphs: [
      'Waitlist emails are kept until you ask us to remove them or unsubscribe. Audit answers are processed to generate your result and are not stored against an identity. Host logs follow our provider’s standard retention.',
    ],
  },
  {
    heading: 'Your choices',
    paragraphs: [
      'Every email we send carries an unsubscribe link. You can also email us at hello@bureauai.com and ask us to delete what we hold about you; we will do it and confirm when it is done. If you are covered by the GDPR, the UK GDPR or the CCPA, the rights those laws give you — access, correction, deletion, portability and objection — apply here regardless of where you live, because it is simpler for us to treat everyone the same way.',
    ],
  },
  {
    heading: 'Children',
    paragraphs: [
      'This is a service for business owners. It is not directed at anyone under 18, and we do not knowingly collect information from them.',
    ],
  },
  {
    heading: 'Changes',
    paragraphs: [
      'If this policy changes materially we will update the date at the top of this page, and we will email the waitlist if the change affects information we already hold.',
    ],
  },
]

export default function PrivacyPage() {
  return (
    <LegalPage
      title="Privacy"
      updated="25 August 2026"
      intro="BureauAI is pre-revenue and collects about as little as a business can while still functioning. This page says plainly what that means rather than describing practices we do not have."
      sections={SECTIONS}
    />
  )
}
