import type { Metadata } from 'next'
import LegalPage, { type Section } from '../_components/LegalPage'

export const metadata: Metadata = {
  title: 'Terms',
  description:
    'The terms covering BureauAI’s website, compliance audit and demo — including what the service is not.',
  alternates: { canonical: '/terms' },
}

const SECTIONS: Section[] = [
  {
    heading: 'What this covers',
    paragraphs: [
      'These terms cover the BureauAI website, the compliance audit, and the department demo. They do not cover a paid engagement, because there is not one yet — BureauAI is pre-revenue and nothing on this site is for sale. When paid service opens, it will carry its own agreement and we will ask you to accept it then.',
    ],
  },
  {
    heading: 'We are not your lawyer',
    paragraphs: [
      'BureauAI is not a law firm, and nothing produced by this site is legal advice or creates an attorney–client relationship. It is also not accounting or tax advice. For a contested hearing, a licence revocation, or anything where the downside is severe, engage a qualified professional. We will tell you when we think you are in that territory.',
    ],
  },
  {
    heading: 'The audit is a starting point, not a guarantee',
    paragraphs: [
      'The compliance audit is generated by an AI model from the four answers you give it. It can be incomplete or wrong. NYC rules, fees and processing times change, and they vary by business type, borough, premises and history in ways four answers cannot fully capture.',
      'Fee figures shown across this site are the city’s published amounts or typical market rates at the time of writing. They are illustrative, not quotes. Verify anything you are about to act on against the relevant agency, and treat the audit as a map of where to look rather than a substitute for looking.',
    ],
  },
  {
    heading: 'Compliance stays yours',
    paragraphs: [
      'Until a paid engagement exists and you have signed one, you remain responsible for your own permits, licences, renewals, filings and violation responses. We do not file anything with any agency on your behalf today, and using this site does not transfer any obligation to us.',
    ],
  },
  {
    heading: 'Demonstration content',
    paragraphs: [
      'The department demo and the sample audit output on the home page run on synthetic data created to show how the product works. They are labelled where they appear. They are not real customers, real filings or real results, and no figure in them should be read as a claim about outcomes BureauAI has produced.',
    ],
  },
  {
    heading: 'Acceptable use',
    bullets: [
      'Do not use the site to break the law, or to help anyone else evade a genuine obligation.',
      'Do not scrape, overload, or attempt to disrupt the service or its underlying providers.',
      'Do not submit another person’s information without the right to do so.',
      'Do not present BureauAI output as the determination of a government agency.',
    ],
  },
  {
    heading: 'Availability',
    paragraphs: [
      'The site is provided as it is, without warranty of any kind. It is an early-stage product: features appear, change and break. We may modify or withdraw any part of it at any time, and we do not promise uptime.',
    ],
  },
  {
    heading: 'Liability',
    paragraphs: [
      'To the fullest extent the law allows, BureauAI is not liable for indirect or consequential loss, or for lost profits, arising from your use of this free site. Nothing here limits liability for fraud, for death or personal injury caused by negligence, or for anything else that cannot lawfully be limited.',
    ],
  },
  {
    heading: 'Governing law',
    paragraphs: [
      'These terms are governed by the laws of the State of New York, and the courts of New York County have exclusive jurisdiction over any dispute arising from them.',
    ],
  },
]

export default function TermsPage() {
  return (
    <LegalPage
      title="Terms"
      updated="25 August 2026"
      intro="Short, and written to be read. The most important part is the second section: BureauAI is not a law firm, and the audit is a starting point rather than a determination."
      sections={SECTIONS}
    />
  )
}
